export const FUNCIONARIOS = [
  {
    matricula: "N� pessoal",
    nome: "Nome",
    cm: "Denom.subgrp.emprg",
    cargo: "Desc.Cargo",
    equipe: "Equipe",
    MOBILIDADE: "MOBILIDADE",
  },
  {
    matricula: "2004452",
    nome: "JOSE LUIZ SCARPELINI",
    cm: "Operacionais",
    cargo: "Eletricista LV de Const. Rede Automat. I",
    equipe: "LV-31",
    MOBILIDADE: "false",
  },
  {
    matricula: "2004463",
    nome: "LUCIANO DE FARIA OLIVEIRA",
    cm: "Administrativos",
    cargo: "Assistente de Manuten��o",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2005968",
    nome: "PAULO AUGUSTO DINIZ BUENO SILVA",
    cm: "Operacionais",
    cargo: "Eletricista LV de Const. Rede Automat. I",
    equipe: "LV-31",
    MOBILIDADE: "false",
  },
  {
    matricula: "2006256",
    nome: "DOUGLAS COSTA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-23",
    MOBILIDADE: "false",
  },
  {
    matricula: "2006264",
    nome: "TALLES YAGO MOREIRA CEZARIO",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "LM-02",
    MOBILIDADE: "false",
  },
  {
    matricula: "2006814",
    nome: "CAYO AUGUSTO MONTEIRO LOPES GALVAO",
    cm: "Operacionais",
    cargo: "Almoxarife",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2006818",
    nome: "MARCO ANTONIO DE OLIVEIRA",
    cm: "Operacionais",
    cargo: "Almoxarife",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2007097",
    nome: "WASHINGTON LUIS MAIA",
    cm: "Operacionais",
    cargo: "Encarregado de Constru��o de Redes I",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2007220",
    nome: "BRUNO RAFAEL INACIO",
    cm: "Operacionais",
    cargo: "Eletricista LV de Const. Rede Automat. I",
    equipe: "LV-32",
    MOBILIDADE: "false",
  },
  {
    matricula: "2007498",
    nome: "JONATAS ANTONIO DOMINGUES DA SILVA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "RESERVA",
    MOBILIDADE: "false",
  },
  {
    matricula: "2007503",
    nome: "WILLIAM DANILO OLIVEIRA BARBOSA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2007515",
    nome: "PAULO HENRIQUE DOS SANTOS ALVES",
    cm: "Operacionais",
    cargo: "T�cnico de Obras de Distribui��o Jr",
    equipe: "VIABILIDADE",
    MOBILIDADE: "false",
  },
  {
    matricula: "2007521",
    nome: "EZIQUIEL VENANCIO AIRES",
    cm: "Operacionais",
    cargo: "Eletricista LV de Const. Rede Automat. I",
    equipe: "LV-30",
    MOBILIDADE: "false",
  },
  {
    matricula: "2007614",
    nome: "DIEGO FERNANDO FELISBINO",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2007617",
    nome: "MATHEUS NOGUEIRA SCARPELINI",
    cm: "Operacionais",
    cargo: "Eletricista LV de Const. Rede Automat. I",
    equipe: "LM-04",
    MOBILIDADE: "false",
  },
  {
    matricula: "2007663",
    nome: "WILLIAM RICARDO TOFOLI",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-25",
    MOBILIDADE: "false",
  },
  {
    matricula: "2007688",
    nome: "EZEQUIAS MATHIAS DE SOUZA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-28",
    MOBILIDADE: "false",
  },
  {
    matricula: "2007690",
    nome: "AMAURI JERONIMO DA COSTA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-24",
    MOBILIDADE: "false",
  },
  {
    matricula: "2007692",
    nome: "ROBERIO DE JESUS VIEIRA",
    cm: "Operacionais",
    cargo: "Eletricista LV de Const. Rede Automat. I",
    equipe: "LV-32",
    MOBILIDADE: "false",
  },
  {
    matricula: "2007759",
    nome: "PAULO HENRIQUE RODRIGUES LEITE",
    cm: "Operacionais",
    cargo: "Encarregado de Constru��o de Redes I",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2007819",
    nome: "ANDRE PONTES DA SILVA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "LM-04",
    MOBILIDADE: "false",
  },
  {
    matricula: "2008055",
    nome: "LUIS CARLOS DE OLIVEIRA",
    cm: "Operacionais",
    cargo: "Almoxarife",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2008091",
    nome: "EDUARDO GARCIA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-40",
    MOBILIDADE: "false",
  },
  {
    matricula: "2008154",
    nome: "RAFAEL DE ALBUQUERQUE COSTA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-23",
    MOBILIDADE: "false",
  },
  {
    matricula: "2008598",
    nome: "VAGNER KELLER",
    cm: "Operacionais",
    cargo: "Eletricista LV de Const. Rede Automat. I",
    equipe: "LV-30",
    MOBILIDADE: "false",
  },
  {
    matricula: "2008664",
    nome: "JOSE CICERO GONCALVES DA SILVA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-19",
    MOBILIDADE: "false",
  },
  {
    matricula: "2008768",
    nome: "DANILO TEREZA ALMEIDA",
    cm: "Operacionais",
    cargo: "Eletricista LV de Const. Rede Automat. I",
    equipe: "LV-31",
    MOBILIDADE: "false",
  },
  {
    matricula: "2008991",
    nome: "MARCELO APARECIDO PERES",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-29",
    MOBILIDADE: "false",
  },
  {
    matricula: "2008997",
    nome: "VALDECI DONIZETI DA COSTA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-20",
    MOBILIDADE: "false",
  },
  {
    matricula: "2009136",
    nome: "WAGNER HENRIQUE DOS SANTOS",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "RESERVA",
    MOBILIDADE: "false",
  },
  {
    matricula: "2009211",
    nome: "ADILSON BERNARDINO DOS SANTOS",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "RESERVA",
    MOBILIDADE: "false",
  },
  {
    matricula: "2009214",
    nome: "JEOVANE DA SILVA MALIGESKI",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-18",
    MOBILIDADE: "false",
  },
  {
    matricula: "2009300",
    nome: "FABIO APARECIDO DE OLIVEIRA CARVALHO",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-27",
    MOBILIDADE: "false",
  },
  {
    matricula: "2009355",
    nome: "NORBERTO SANCHES JUNIOR",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-29",
    MOBILIDADE: "false",
  },
  {
    matricula: "2009708",
    nome: "JOSE ROMEU ANTUNES LIMA",
    cm: "Operacionais",
    cargo: "Eletricista Constru��o Manuten��o de IP",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2009719",
    nome: "LEANDRO LUCIANO FRANCO RAMOS",
    cm: "Operacionais",
    cargo: "T�cnico de Obras de Distribui��o Jr",
    equipe: "AFASTADO",
    MOBILIDADE: "false",
  },
  {
    matricula: "2009735",
    nome: "FABIO BENEDITO DE ARAUJO",
    cm: "Operacionais",
    cargo: "Eletricista Constru��o Manuten��o de IP",
    equipe: "LM-03",
    MOBILIDADE: "false",
  },
  {
    matricula: "2010009",
    nome: "LUCIANO DANIEL",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-17",
    MOBILIDADE: "false",
  },
  {
    matricula: "2010137",
    nome: "ITALO ROGERIO DE JESUS CANDIDO MARCHI",
    cm: "Operacionais",
    cargo: "Agente de Log�stica I",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2010224",
    nome: "RENATO LOPES DE SOUZA",
    cm: "Operacionais",
    cargo: "Eletricista Constru��o Manuten��o de IP",
    equipe: "GD-26",
    MOBILIDADE: "false",
  },
  {
    matricula: "2010231",
    nome: "RICARDO CONCEICAO DE ALMEIDA",
    cm: "Operacionais",
    cargo: "Eletricista Constru��o Manuten��o de IP",
    equipe: "GD-26",
    MOBILIDADE: "false",
  },
  {
    matricula: "2010261",
    nome: "ANTONIO AUREO FRANCA",
    cm: "Operacionais",
    cargo: "Eletricista LV de Const. Rede Automat. I",
    equipe: "GD-18",
    MOBILIDADE: "false",
  },
  {
    matricula: "2010655",
    nome: "RAPHAEL CALISTRO",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "VIABILIDADE",
    MOBILIDADE: "false",
  },
  {
    matricula: "2010657",
    nome: "DAVID WILLIAM DOS SANTOS MIONI",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-40",
    MOBILIDADE: "false",
  },
  {
    matricula: "2010697",
    nome: "ELTON SANTUCCI DE OLIVEIRA",
    cm: "Operacionais",
    cargo: "Agente de Log�stica I",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2010766",
    nome: "JONATHAN HENRIQUE DOS SANTOS BERNARDO",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-17",
    MOBILIDADE: "false",
  },
  {
    matricula: "2011657",
    nome: "ERYKE FERNANDES PEREIRA DA SILVA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-20",
    MOBILIDADE: "false",
  },
  {
    matricula: "2011668",
    nome: "ANTONIO MARCOS MININELE",
    cm: "Operacionais",
    cargo: "Encarregado de Constru��o de Redes I",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2011672",
    nome: "LUIZ HENRIQUE ALEXANDRE MORAES",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "LM-01",
    MOBILIDADE: "false",
  },
  {
    matricula: "2011681",
    nome: "WELBER JULIARDI DA SILVA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-25",
    MOBILIDADE: "false",
  },
  {
    matricula: "2011774",
    nome: "LUIZ ANTONIO ALVES DA SILVA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "RESERVA",
    MOBILIDADE: "false",
  },
  {
    matricula: "2011787",
    nome: "WELLINGTON DE LIMA BUENO",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-29",
    MOBILIDADE: "false",
  },
  {
    matricula: "2011917",
    nome: "LEANDRO CARLOS SARDINHA DOS SANTOS",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "ALMOXARIFADO",
    MOBILIDADE: "false",
  },
  {
    matricula: "2012247",
    nome: "JOSE HENRIQUE DA COSTA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-27",
    MOBILIDADE: "false",
  },
  {
    matricula: "2012387",
    nome: "ANDRE EUZEBIO DE SOUZA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "AFASTADO",
    MOBILIDADE: "false",
  },
  {
    matricula: "2012395",
    nome: "FABIO JESUS DOS SANTOS",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-26",
    MOBILIDADE: "false",
  },
  {
    matricula: "2012405",
    nome: "CARLOS EDUARDO FONSECA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-19",
    MOBILIDADE: "false",
  },
  {
    matricula: "2012409",
    nome: "AGNALDO CESAR NUNES",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-22",
    MOBILIDADE: "false",
  },
  {
    matricula: "2012483",
    nome: "RAFAEL HENRIQUE DE ASSIS",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "RESERVA",
    MOBILIDADE: "false",
  },
  {
    matricula: "2012702",
    nome: "FELIPE BORGES PAES",
    cm: "Mirins",
    cargo: "GUARDA MIRIM / PATRULHEIRO",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2013254",
    nome: "JOSE EDUARDO BRITO ALVES",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-21",
    MOBILIDADE: "false",
  },
  {
    matricula: "2013957",
    nome: "DANILO DINIZ DA SILVA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-19",
    MOBILIDADE: "false",
  },
  {
    matricula: "2013976",
    nome: "ANDERSON FERNANDO BOLONHESI DE BRITO",
    cm: "Operacionais",
    cargo: "Ajudante de Eletricista Const. Rede Auto",
    equipe: "GD-25",
    MOBILIDADE: "false",
  },
  {
    matricula: "2014000",
    nome: "MARIO ARAUJO DE CARVALHO",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-22",
    MOBILIDADE: "false",
  },
  {
    matricula: "2014041",
    nome: "MAURILIO PIRES",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "RESERVA",
    MOBILIDADE: "false",
  },
  {
    matricula: "2014317",
    nome: "LUIS FABIANO CALIXTO",
    cm: "Operacionais",
    cargo: "Agente de Log�stica I",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2014415",
    nome: "MOISES ANDRADE DOS SANTOS",
    cm: "Operacionais",
    cargo: "Ajudante de Eletricista Const. Rede Auto",
    equipe: "LM-02",
    MOBILIDADE: "false",
  },
  {
    matricula: "2014416",
    nome: "JORGE LUIZ DIONISIO",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "LM-03",
    MOBILIDADE: "false",
  },
  {
    matricula: "2014422",
    nome: "JOSE CARDOSO AMANCIO DOS SANTOS",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-20",
    MOBILIDADE: "false",
  },
  {
    matricula: "2014425",
    nome: "TIAGO LUIZ ANGELO",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-23",
    MOBILIDADE: "false",
  },
  {
    matricula: "2014435",
    nome: "ROGERIO SANTOS DA COSTA",
    cm: "Operacionais",
    cargo: "Almoxarife",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2014697",
    nome: "VICENTE GIOVANI DA SILVA",
    cm: "Operacionais",
    cargo: "Ajudante de Eletricista Const. Rede Auto",
    equipe: "RESERVA",
    MOBILIDADE: "false",
  },
  {
    matricula: "2014704",
    nome: "FLAVIO AUGUSTO SIMOES MARTINS",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-21",
    MOBILIDADE: "false",
  },
  {
    matricula: "2015199",
    nome: "GILMAR PEREIRA BORGES",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-28",
    MOBILIDADE: "false",
  },
  {
    matricula: "2015667",
    nome: "FILLIPE HENRIQUE DA SILVA SOUZA",
    cm: "Operacionais",
    cargo: "Ajudante de Eletricista Const. Rede Auto",
    equipe: "GD-18",
    MOBILIDADE: "false",
  },
  {
    matricula: "2016323",
    nome: "MAICON EVERTON PEREIRA DA SILVA",
    cm: "Operacionais",
    cargo: "Almoxarife",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2016559",
    nome: "AUGUSTO CESAR DA SILVA CORREA",
    cm: "Operacionais",
    cargo: "Almoxarife",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2017090",
    nome: "VALDEMIR ARRUDA DA SILVA",
    cm: "Operacionais",
    cargo: "Ajudante de Eletricista Const. Rede Auto",
    equipe: "GD-27",
    MOBILIDADE: "false",
  },
  {
    matricula: "2017097",
    nome: "FELIPE GUSTAVO SILVA MASCARENHAS",
    cm: "Operacionais",
    cargo: "Ajudante de Eletricista Const. Rede Auto",
    equipe: "GD-24",
    MOBILIDADE: "false",
  },
  {
    matricula: "2017213",
    nome: "ANDRE LEONARDO DOS SANTOS",
    cm: "Operacionais",
    cargo: "Ajudante de Eletricista Const. Rede Auto",
    equipe: "GD-17",
    MOBILIDADE: "false",
  },
  {
    matricula: "2017215",
    nome: "CESAR AUGUSTO DIAS DE SOUZA RODRIGUES",
    cm: "Operacionais",
    cargo: "Ajudante de Eletricista Const. Rede Auto",
    equipe: "GD-21",
    MOBILIDADE: "false",
  },
  {
    matricula: "2017217",
    nome: "ATANIEL DE JESUS SOARES",
    cm: "Administrativos",
    cargo: "Coordenador de Base Operacional I",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2017221",
    nome: "JONATAS JOSE PIEDADE SILVA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-24",
    MOBILIDADE: "false",
  },
  {
    matricula: "2017294",
    nome: "CAMILA SANTOS DE OLIVEIRA",
    cm: "Operacionais",
    cargo: "Almoxarife",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2018048",
    nome: "ALESSANDRO MARCIANO",
    cm: "Operacionais",
    cargo: "Almoxarife",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2018049",
    nome: "JOVIANO CONSTANTINO MONTEIRO",
    cm: "Administrativos",
    cargo: "Assistente de Manuten��o",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2018056",
    nome: "MARCOS GABRIEL DE LALLA",
    cm: "Operacionais",
    cargo: "Almoxarife",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2018057",
    nome: "GUILHERME ALEXANDRE CARDOSO VIZON",
    cm: "Operacionais",
    cargo: "Almoxarife",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2018089",
    nome: "BERNARDO VICENTINI NOGUEIRA DUARTE",
    cm: "Operacionais",
    cargo: "Almoxarife",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "2018836",
    nome: "JOSE EDINALDO SERAFIM DE ANDRADE",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. III",
    equipe: "GD-28",
    MOBILIDADE: "false",
  },
  {
    matricula: "3004507",
    nome: "GILDECIO FABIO DA COSTA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. II",
    equipe: "GD-29",
    MOBILIDADE: "false",
  },
  {
    matricula: "8000652",
    nome: "ALDELINO MAIGO COELHO",
    cm: "Operacionais",
    cargo: "Encarregado de Constru��o de Redes I",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "8001244",
    nome: "JOAO CORREA DA SILVA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "RESERVA",
    MOBILIDADE: "false",
  },
  {
    matricula: "8001252",
    nome: "HERCULES APARECIDO DE MORAES",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. II",
    equipe: "LM-01",
    MOBILIDADE: "false",
  },
  {
    matricula: "8001343",
    nome: "DOUGLAS PEREIRA DA SILVA",
    cm: "Operacionais",
    cargo: "Encarregado de Constru��o de Redes I",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "8001355",
    nome: "ANGELICA CRISTINA MORES",
    cm: "Administrativos",
    cargo: "Assistente Administrativo Opera� Serv Pl",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "8001405",
    nome: "PAULO HENRIQUE CERICO PALERMO",
    cm: "Operacionais",
    cargo: "Agente de Log�stica I",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "8001883",
    nome: "RINALDO DE OLIVEIRA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-22",
    MOBILIDADE: "false",
  },
  {
    matricula: "8001884",
    nome: "ARLEN NOGUEIRA SILVA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. II",
    equipe: "GD-28",
    MOBILIDADE: "false",
  },
  {
    matricula: "8001918",
    nome: "ADEMIR PEREIRA DA SILVA",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "MONTADOR",
    MOBILIDADE: "false",
  },
  {
    matricula: "8003129",
    nome: "BRUNO HENRIQUE VIEIRA",
    cm: "Operacionais",
    cargo: "Almoxarife",
    equipe: "ADM",
    MOBILIDADE: "false",
  },
  {
    matricula: "8003460",
    nome: "CLEBER MOISES DE ASSIS NOGUEIRA",
    cm: "Operacionais",
    cargo: "Eletricista LV de Const. Rede Automat. I",
    equipe: "LV-33",
    MOBILIDADE: "false",
  },
  {
    matricula: "8003461",
    nome: "DAVID APARECIDO DA SILVA GERALDO",
    cm: "Operacionais",
    cargo: "Eletricista de Const. Rede Autom. I",
    equipe: "GD-28",
    MOBILIDADE: "false",
  },
  {
    matricula: "8003464",
    nome: "FELIPE OTAVIO HENRIQUE BASSO",
    cm: "Operacionais",
    cargo: "Eletricista LV de Const. Rede Automat. I",
    equipe: "LV-33",
    MOBILIDADE: "false",
  },
];
